name: Build Next.js web application
on: push
jobs:
    build-project:
        name: Build project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install NPM dependencies
              run: npm install
            - name: Buuild project assests
              run: npm run build